web:
  build: .
  command: npm run start
  volumes:
    - .:/var/app
  ports:
    - "5000:5000"
  environment:
    - API_SECRET=zipper
test:
  build: .
  command: npm run test
  links:
    - web
  volumes:
    - .:/var/app
  environment:
    - ZIPPER_URL=http://zipper:zipper@web:5000
